"""new tables

Revision ID: 60b246c2a8c0
Revises: 986a207ee025
Create Date: 2026-08-30 07:40:42.677058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes
# revision identifiers, used by Alembic.
revision: str = '60b246c2a8c0'
down_revision: Union[str, Sequence[str], None] = '986a207ee025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:cl
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bg_img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_workspace_id'), 'boards', ['workspace_id'], unique=False)
    op.create_table('lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_board_id'), 'lists', ['board_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_list_id'), 'cards', ['list_id'], unique=False)
    op.create_table('checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_card_id'), 'checklists', ['card_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checklist_id', sa.Uuid(), nullable=False),
    sa.Column('val', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['checked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_checked_by'), 'checklist_items', ['checked_by'], unique=False)
    op.create_index(op.f('ix_checklist_items_checklist_id'), 'checklist_items', ['checklist_id'], unique=False)
    op.drop_table('board')
    op.add_column('workspace_member', sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='workspacerole'), nullable=False))
    op.alter_column('workspace_member', 'workspace_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_member', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_member', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workspaces', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.drop_constraint(None, 'workspace_member', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_member', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'workspace_member', 'users', ['user_id'], ['id'])
    op.alter_column('workspace_member', 'workspace_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('workspace_member', 'role')
    op.create_table('board',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_checklist_items_checklist_id'), table_name='checklist_items')
    op.drop_index(op.f('ix_checklist_items_checked_by'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_checklists_card_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_cards_list_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_lists_board_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_boards_workspace_id'), table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###
