"""new index in boards and checklist item


Revision ID: 6b94cfd0a883
Revises: 
Create Date: 2026-09-04 05:32:49.155624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b94cfd0a883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_position', 'checklist_items', ['checklist_id', 'position'], unique=False)
    op.create_index('ix_board_position', 'lists', ['board_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_board_position', table_name='lists')
    op.drop_index('ix_item_position', table_name='checklist_items')
    # ### end Alembic commands ###
