"""Index the field due_date in cards

Revision ID: a325fbb2c5fb
Revises: 6b94cfd0a883
Create Date: 2026-09-04 05:49:33.568870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a325fbb2c5fb'
down_revision: Union[str, Sequence[str], None] = '6b94cfd0a883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cards_due_date'), 'cards', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_due_date'), table_name='cards')
    # ### end Alembic commands ###
